using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.Rendering;
using SashimiBoy.Semantics;
using Object=UnityEngine.Object;

namespace SashimiBoy.EditorTools
{
    public static partial class Stage02RockfishAuthoring
    {
        public const string Root="Assets/_SashimiBoy/Art/Generated/Stage02Rockfish";
        public const string ScenePath="Assets/_SashimiBoy/Scenes/Stage02_Rockfish.unity";
        public const string SourcePrefab="Assets/_SashimiBoy/Art/Generated/Prefabs/FishShop/PF_Fish_Rockfish.prefab";
        public const string MusicPath="Assets/_SashimiBoy/Audio/Music/Stage_02_Rockfish/rockfish1.mp3";
        public const string FleshPath="Assets/_SashimiBoy/Art/Resources/Stage02Rockfish/rockfish_crosssection.png";
        public const string PatternPath="Assets/_SashimiBoy/Data/Generated/Stage02NotePattern.asset";
        public const string ChartPath="Assets/_SashimiBoy/Data/Generated/Stage02SemanticBeatmap.asset";

        public static void AuditModelReapplyBatch()
        {
            string Hash(string path) { using(var sha=System.Security.Cryptography.SHA256.Create())return Convert.ToBase64String(sha.ComputeHash(File.ReadAllBytes(path))); }
            var before=Directory.GetFiles(Root,"*",SearchOption.AllDirectories).ToDictionary(p=>p,p=>Hash(p));
            BuildModels(12);
            var changed=before.Keys.Where(p=>!File.Exists(p)||Hash(p)!=before[p]).ToArray();
            if(changed.Length>0 || Directory.GetFiles(Root,"*",SearchOption.AllDirectories).Length!=before.Count)
                throw new InvalidOperationException("Stage02 model reapply changed generated bytes: "+string.Join(", ",changed));
            Debug.Log("[Stage02] Model reapply byte stability: "+before.Count+" files unchanged.");
        }

        public static void InspectSourceBatch()
        {
            DayWorldStreetAuthoring.BuildDoorModels();
            var scene=EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);
            var fish=Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>(SourcePrefab));
            var camera=new GameObject("InspectCamera",typeof(Camera)).GetComponent<Camera>();
            camera.clearFlags=CameraClearFlags.SolidColor;camera.backgroundColor=new Color(.14f,.17f,.19f);
            camera.fieldOfView=43f;
            var light=new GameObject("InspectLight",typeof(Light)).GetComponent<Light>();
            light.type=LightType.Directional;light.intensity=1.3f;light.transform.rotation=Quaternion.Euler(45f,-30f,0);
            RenderSettings.ambientMode=AmbientMode.Flat;RenderSettings.ambientLight=Color.gray;
            foreach(int roll in new[]{0,90,-90})
            {
                fish.transform.rotation=Quaternion.Euler(roll,0,0);
                Bounds b=DayWorldAssetAuthoring.HomeGeometryBounds(fish);
                Debug.Log("[RockfishSource] roll="+roll+" bounds="+b);
                camera.transform.position=b.center+new Vector3(.1f,1.5f,-1.5f);camera.transform.LookAt(b.center);
                CaptureCamera(camera,"Logs/DayWorld/StreetDoorsStage2Revision/rockfish-source-"+roll+".png");
            }
            var filters=fish.GetComponentsInChildren<MeshFilter>();
            foreach(var f in filters) Debug.Log("[RockfishMesh] "+f.name+" vertices="+f.sharedMesh.vertexCount+" bounds="+f.sharedMesh.bounds);
        }

        private static void CaptureCamera(Camera camera,string path)
        {
            var target=new RenderTexture(1200,800,24);var before=RenderTexture.active;
            camera.targetTexture=target;camera.Render();RenderTexture.active=target;
            var texture=new Texture2D(1200,800,TextureFormat.RGB24,false);
            texture.ReadPixels(new Rect(0,0,1200,800),0,0);texture.Apply();
            File.WriteAllBytes(path,texture.EncodeToPNG());camera.targetTexture=null;RenderTexture.active=before;
            Object.DestroyImmediate(texture);Object.DestroyImmediate(target);
        }
    }
}
